import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Internship from "../components/Internship";
import Intro from "../components/Intro";
import Links from "../components/Links";
import Projects from "../components/Projects";
import Skills from "../components/Skills";

export default function Home() {
  return (
    <div>
      <Head>
        <title>attarranggaaa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex justify-center py-32 bg-black min-h-screen">
          <div className="w-[30rem] text-white space-y-12 px-4 selection:bg-emerald-300 selection:text-black">
            <Intro />
            <About />
            <Internship />
            <Skills />
            <Projects />
            <Links />
          </div>
        </div>
      </main>
    </div>
  );
}
